import type { APIRoute } from 'astro';
import { env } from 'cloudflare:workers';
import { d1AdminIssueStore, issueFromQueue, refuseFromQueue } from '../../../lib/admin-issue.ts';
import { isBand } from '../../../lib/licence.ts';
import { createMailer, transportFromEnv } from '../../../lib/email/mailer.ts';
import { emailLinkBaseUrl } from '../../../config';

export const prerender = false;

/**
 * The signing secrets. Declared here rather than in `worker-configuration.d.ts` because that file is
 * GENERATED by `wrangler types`, which infers secret names from a local `.dev.vars` — so a regeneration on
 * a machine without them would silently drop the declarations. Set in production with
 * `wrangler secret put`; documented in `.dev.vars.example`.
 *
 * ⛔ SIGNING_KEY_JWK IS THE PRIVATE KEY AND THE WHOLE COMMERCIAL MODEL. It is read here, passed to the
 * signer, and never returned, logged or serialised — see src/lib/licence.ts.
 */
interface SigningEnv {
  SIGNING_KEY_JWK?: string;
  SIGNING_KID?: string;
  SIGNING_PUBLIC_JWK?: string;
  ADMIN_TOKEN?: string;
}
const secrets = env as unknown as SigningEnv;

/**
 * ⛔ THE ONLY MINTING SITE IN THIS CODEBASE, AND IT IS REACHED ONLY BY A PERSON.
 *
 * Dispositioned explicitly in issuance-gate.test.ts under MINTING.allowedIn — not by widening a pattern.
 * The guard's whole value is that every minting site is NAMED; an exemption that is a wildcard is a hole.
 *
 * Manual issuance is founder-ruled: offline verification means no revocation, so an automated mint is a
 * mistake that cannot be taken back. The unattended paths (verify.ts, worker.ts/cron) hold deferring
 * issuers and cannot reach this code.
 */
export const POST: APIRoute = async ({ request }) => {
  // ⚠ Bearer OR the HttpOnly cookie the queue page sets — the token no longer travels in a URL (F4).
  const bearer = (request.headers.get('authorization') ?? '').replace(/^Bearer /, '');
  const cookie = /(?:^|;\s*)tnx_admin=([^;]+)/.exec(request.headers.get('cookie') ?? '')?.[1];
  const token = bearer || (cookie ? decodeURIComponent(cookie) : '');
  if (!adminAuthed(token)) return new Response('unauthorized', { status: 401 });

  const body = (await request.json()) as {
    domain?: string;
    refuse?: boolean;
    action?: 'settle' | 'band' | 'direct';
    band?: string;
    contactEmail?: string;
    termMonths?: number;
    notes?: string;
  };
  const domain = String(body.domain ?? '')
    .trim()
    .toLowerCase();
  if (!domain) return new Response('domain required', { status: 400 });

  const store = d1AdminIssueStore(env.DB);
  const now = Math.floor(Date.now() / 1000);

  if (body.action === 'settle') {
    // ⛔ RECORDING A FACT ABOUT THE WORLD, NOT A PERMISSION. The money arrived or it did not; this row is
    // only how we remember which. Refuses on anything that is not a pending paid row, so it cannot be
    // replayed and cannot "settle" a trial that has nothing to settle.
    const ok = await store.settlePayment(domain, now);
    return new Response(ok ? 'payment recorded — the row is now signable' : 'not a pending paid row', {
      status: ok ? 200 : 409,
    });
  }

  if (body.action === 'band') {
    // ⛔ THE REVIEWER SETS THE BAND. The requester's asked-for band is recorded beside it and never signed.
    const band = String(body.band ?? '');
    if (!isBand(band)) return new Response(`unknown band: ${band}`, { status: 400 });
    const ok = await store.setBand(domain, band);
    return new Response(ok ? `band set to ${band}` : 'row is already decided', {
      status: ok ? 200 : 409,
    });
  }

  if (body.action === 'direct') {
    // ⭐ A DEAL CLOSED OFFLINE, OR A RE-ISSUE — THE SAME THING FROM TWO ENTRY POINTS. It FILES a row; it
    // does not sign one. A second minting site would be a second place for the ordering rules
    // (claim → mint → self-verify → record → send) to drift, and those rules exist because each step's
    // failure is unrecoverable in a different way.
    const band = String(body.band ?? '');
    const contactEmail = String(body.contactEmail ?? '').trim();
    const termMonths = Number(body.termMonths ?? 0);
    if (!isBand(band)) return new Response(`unknown band: ${band}`, { status: 400 });
    if (!contactEmail.includes('@')) return new Response('a contact address is required', { status: 400 });
    if (!Number.isInteger(termMonths) || termMonths < 1 || termMonths > 60) {
      return new Response('term must be 1–60 months', { status: 400 });
    }
    const outcome = await store.createDirect({
      domain,
      band,
      contactEmail,
      termMonths,
      issuedAt: now,
      expiresAt: now + termMonths * 30 * 24 * 60 * 60,
      licenseId: crypto.randomUUID(),
      notes: String(body.notes ?? ''),
    });
    return outcome === 'queued'
      ? new Response(`filed for ${domain} — review and sign it in the queue`)
      : new Response(
          `a request for ${domain} is already open — settle or refuse that one first`,
          { status: 409 },
        );
  }

  if (body.refuse) {
    const r = await refuseFromQueue({ store }, domain);
    return new Response(r.ok ? 'refused' : 'already decided', { status: r.ok ? 200 : 409 });
  }

  const row = (await store.pendingQueue()).find((q) => q.domain === domain);
  if (!row) return new Response('no such pending row', { status: 404 });

  const mailer = createMailer({ transport: transportFromEnv(env), baseUrl: emailLinkBaseUrl });
  const result = await issueFromQueue(
    {
      store,
      env: secrets,
      async sendKey(to, dom, licenceKey, expiresAt) {
        const expiry = new Date(expiresAt * 1000).toISOString().slice(0, 10);
        // ⛔ THE TRIAL TEMPLATE IS NOT A GENERIC KEY TEMPLATE. It promises a free evaluation and says
        // enforcement is not live — copy that would be false in a paying customer's inbox, and the kind of
        // false that reads as a refund conversation. Two kinds, chosen by the row.
        if (row.kind === 'trial') {
          await mailer.send('trial-key-delivery', to, {
            domain: dom,
            licenseKey: licenceKey,
            expiresAt: expiry,
          });
          return;
        }
        await mailer.send('licence-key-delivery', to, {
          domain: dom,
          band: row.tier,
          licenseKey: licenceKey,
          expiresAt: expiry,
        });
      },
    },
    row,
  );

  if (result.ok && result.emailed) return new Response(`issued and emailed to ${row.contactEmail ?? row.trialEmail}`);
  if (result.ok) {
    // ⚠ NEVER SILENT. The key is minted and unrevocable; losing it helps nobody.
    return new Response(
      `ISSUED, BUT NOT EMAILED (${result.deliveryError}).\nSend this to ${row.contactEmail ?? row.trialEmail} manually:\n\n${result.licenceKey}`,
      { status: 200 },
    );
  }
  if (result.code === 'minted_but_unrecorded') {
    // ⛔ The one state a human must reconcile. Loud, with the key, and a 500 so it cannot read as routine.
    return new Response(
      `⛔ MINTED BUT NOT RECORDED (${result.detail}).\nA LIVE KEY EXISTS AND IS NOT IN THE LEDGER. Record it by hand:\n\n${result.licenceKey}`,
      { status: 500 },
    );
  }
  // ⚠ THE REASON AND THE DETAIL BOTH REACH THE OPERATOR. "sign_failed" alone gave them no way to tell a
  // malformed secret from a key this runtime refuses — and the second is not a paste error, it is the
  // ceremony emitting the wrong thing. `detail` carries the exception's name and message, never a value.
  const hint: Partial<Record<string, string>> = {
    // ⛔ THE REFUSAL THE BUTTON ALSO EXPRESSES, SAID BY THE SERVER. A disabled control is a statement about
    // a DOM; this endpoint is reachable without it.
    payment_not_settled:
      'This is a PAID request and the money has not been recorded as arrived. Mark the payment received ' +
      'on the queue first — a paid key is a year long and cannot be recalled.',
    signing_key_unreadable:
      'SIGNING_KEY_JWK is absent or not valid JSON — re-run the ceremony in README.md.',
    signing_key_rejected:
      'The signing key parsed but this runtime refused it. Most likely alg: Node exports "Ed25519", ' +
      'Workers requires "EdDSA". Re-run the ceremony — it now emits EdDSA — then hit /api/admin/signing-selftest.',
    signing_threw: 'The key imported but signing failed.',
    self_verify_failed:
      'SIGNING_PUBLIC_JWK is not the public half of SIGNING_KEY_JWK. Nothing was issued.',
  };
  const extra = [hint[result.code], result.detail].filter(Boolean).join('\n');
  return new Response(extra ? `${result.code}\n\n${extra}` : result.code, {
    status: result.code === 'not_pending' ? 409 : 400,
  });
};

/** Constant-time compare: a `===` on the only secret guarding the signer leaks its prefix by timing. */
function adminAuthed(token: string): boolean {
  const expected = secrets.ADMIN_TOKEN;
  if (!expected || token.length !== expected.length) return false;
  let diff = 0;
  for (let i = 0; i < token.length; i++) diff |= token.charCodeAt(i) ^ expected.charCodeAt(i);
  return diff === 0;
}
